class Brackets2 {

    synchronized public static void generate(String threadCode){
        for (int i=1;i<=10;i++){
            if(i<=5)
                System.out.print("{");
            else
                System.out.print("}");
        }
        System.out.println("Generated by thread : "+threadCode);
    }
}
public class StaticSynchronization {
    public static void main(String[] args) {

        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i=1; i<=5; i++){
                    Brackets2.generate("T1");
                }
            }
        }).start();

        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i=1; i<=5; i++) {
                    Brackets2.generate("T2");
                }
            }
        }).start();
    }
}
